CREATE TABLE HOTELS  (
    ID INT PRIMARY KEY,
    NAME VARCHAR(250),
    DESCRIPTION VARCHAR(250),
    CITY VARCHAR(250),
    RATING VARCHAR(250),
    ATIVO VARCHAR(3)
 );
  
ALTER TABLE HOTELS DROP PRIMARY KEY;
